project:
  type: book

output: html_document
engine: knitr

book:
  title: "Shell genomics"
  #author: "Jane Doe"
  date: "8/9/2022"
  search: true
  sharing: [twitter, facebook]
  chapters:
    - index.qmd
    - intro.qmd
    - navigation.qmd
    - work-with-files-and-dir.qmd
    - redirection.qmd
    - scripting.qmd
    - organisation.qmd
    - references.qmd

execute:
  echo: false

jupyter: python3

bibliography: references.bib

format:
  html:
    theme: cosmo
    default-image-extension: svg

editor: visual

comments:
  hypothesis: true
  
code-copy: false
