project:
  type: book
  output-dir: docs

output: html_document
engine: knitr

book:
  title: "Shell genomics"
  #author: "Jane Doe"
  date: "11/15/2023"
  search: true
  sharing: [twitter, facebook]
  chapters:
    - index.qmd
    - intro.qmd
    - navigation.qmd
    - work-with-files-and-dir.qmd
    - redirection.qmd
    - scripting.qmd
    - organisation.qmd
    - references.qmd

execute:
  echo: false

jupyter: python3

bibliography: references.bib

format:
  html:
    theme: cosmo
    other-links:
      - text: Introduction to Genomics Chatbot
        href: https://tsl-bioinformatics.shinyapps.io/genomics_chatbot/
        target: _blank
  pdf:
    documentclass: scrreprt

comments:
  hypothesis: true
  
code-copy: false
